import unittest

from backend.main import FRONTEND_DIR, app, app_index, cli_wizard


class FrontendTest(unittest.TestCase):
    def test_frontend_assets_exist(self) -> None:
        self.assertTrue((FRONTEND_DIR / "index.html").exists())
        self.assertTrue((FRONTEND_DIR / "styles.css").exists())
        self.assertTrue((FRONTEND_DIR / "app.js").exists())
        self.assertIn("X-Request-ID", (FRONTEND_DIR / "app.js").read_text(encoding="utf-8"))
        self.assertIn("12000", (FRONTEND_DIR / "app.js").read_text(encoding="utf-8"))
        self.assertIn("message = apiDetailText(payload.detail) || message", (FRONTEND_DIR / "app.js").read_text(encoding="utf-8"))

    def test_cli_wizard_assets_and_route_exist(self) -> None:
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        wizard_html = (FRONTEND_DIR / "cli-wizard.html").read_text(encoding="utf-8")
        wizard_js = (FRONTEND_DIR / "cli-wizard.js").read_text(encoding="utf-8")

        self.assertIn('id="cliWizardLink"', index_html)
        self.assertIn('id="appVersion"', index_html)
        self.assertIn('id="appVersion"', wizard_html)
        self.assertIn('href="/cli-wizard"', index_html)
        self.assertTrue((FRONTEND_DIR / "cli-wizard.css").exists())
        self.assertIn('id="configSelect"', wizard_html)
        self.assertIn('id="commandPreview"', wizard_html)
        self.assertIn('id="reportChoiceList"', wizard_html)
        self.assertIn('id="selectAllReportsBtn"', wizard_html)
        self.assertIn('id="runExportBtn"', wizard_html)
        self.assertIn('id="downloadCommandBtn"', wizard_html)
        self.assertIn("PowerShell-Automatisierung", wizard_html)
        self.assertIn('fetch("/api/configs"', wizard_js)
        self.assertIn('deficienciesOnly: "false"', wizard_js)
        self.assertIn('fetch("/api/cli-wizard/export"', wizard_js)
        self.assertIn("function loadReports", wizard_js)
        self.assertIn("function runExport", wizard_js)
        self.assertIn("function downloadCommand", wizard_js)
        self.assertIn("state.selectedReports", wizard_js)
        self.assertIn("Invoke-RestMethod", wizard_js)
        self.assertIn("/api/cli-wizard/export", wizard_js)
        self.assertIn('fetch("/api/health"', wizard_js)
        self.assertIn("Tenant wird automatisch als Unterordner", wizard_html)
        self.assertNotIn("nemo_import_export.py", wizard_js)
        self.assertEqual(FRONTEND_DIR / "cli-wizard.html", cli_wizard().path)
        self.assertIn("/cli-wizard", {getattr(route, "path", "") for route in app.routes})
        self.assertIn("/api/cli-wizard/export", {getattr(route, "path", "") for route in app.routes})

    def test_stale_editor_model_response_is_discarded_after_report_change(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")

        self.assertIn("editorLoadToken", app_js)
        self.assertIn("loadToken !== state.editorLoadToken", app_js)
        self.assertIn("requestedReportRef !== reportRef(state.selectedReport || {})", app_js)

    def test_root_route_returns_index_file(self) -> None:
        response = app_index()

        self.assertEqual(FRONTEND_DIR / "index.html", response.path)

    def test_app_registers_frontend_and_api_routes(self) -> None:
        route_paths = {getattr(route, "path", "") for route in app.routes}

        self.assertIn("/", route_paths)
        self.assertIn("/assets", route_paths)
        self.assertIn("/api/rule-catalog", route_paths)
        self.assertIn("/api/ai/messages/translate", route_paths)
        self.assertIn("/api/harmonization", route_paths)
        self.assertIn("/api/harmonization/preview", route_paths)
        self.assertIn("/api/harmonization/apply", route_paths)
        self.assertIn("/api/rule-templates", route_paths)
        self.assertIn("/api/rule-templates/{template_ref}/resolve", route_paths)
        self.assertIn("/api/rule-templates/candidate-decisions", route_paths)
        self.assertIn("/api/rule-template-bindings", route_paths)

    def test_global_rule_catalog_can_be_managed_and_applied(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="ruleTemplateCatalogBtn"', index_html)
        self.assertIn('id="ruleTemplateCatalogDialog"', index_html)
        self.assertIn('id="ruleTemplateParametersInput"', index_html)
        self.assertIn("openRuleTemplateCatalog", app_js)
        self.assertIn("saveRuleTemplate", app_js)
        self.assertIn("openCatalogRuleWizard", app_js)
        self.assertIn("catalogTemplateId", app_js)
        self.assertIn('requestJson("/api/rule-template-bindings"', app_js)
        self.assertIn(".rule-template-layout", styles_css)
        self.assertIn(".catalog-rule-preview", styles_css)

    def test_ui_and_report_languages_are_selected_independently(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        route_paths = {getattr(route, "path", "") for route in app.routes}

        self.assertIn('id="uiLanguageSelect"', index_html)
        self.assertIn('id="reportLanguageSelect"', index_html)
        self.assertIn("UI_LANGUAGE_STORAGE_KEY", app_js)
        self.assertIn("REPORT_LANGUAGE_STORAGE_KEY", app_js)
        self.assertIn('requestJson("/api/ai/messages/translate"', app_js)
        self.assertIn("messageLanguage", app_js)
        self.assertIn("/api/ai/configs", route_paths)
        self.assertIn("/api/ai/configs/{ai_config_id}/test", route_paths)
        self.assertIn("/api/ai/rules/draft", route_paths)
        self.assertIn("/api/ai/rules/test-examples", route_paths)
        self.assertIn("/api/ai/rules/explain", route_paths)
        self.assertIn("/api/ai/rules/revise", route_paths)
        self.assertIn("/api/ai/fields/suggest-rules", route_paths)
        self.assertIn("/api/configs/from-credentials", route_paths)
        self.assertIn("/api/editor-model/validate", route_paths)
        self.assertIn("/api/projects/{project}/columns", route_paths)
        self.assertIn("/api/config-statistics/report.pdf", route_paths)
        self.assertIn("/api/config-statistics/report.xlsx", route_paths)
        self.assertIn("/api/reports", route_paths)
        self.assertIn("/api/reports/{report_ref}/editor-model", route_paths)
        self.assertIn("/api/reports/{report_ref}/draft", route_paths)
        self.assertIn("/api/reports/{report_ref}/change-log", route_paths)
        self.assertIn("/api/reports/{report_ref}/change-log/undo", route_paths)
        self.assertIn("/api/reports/{report_ref}/restore-original", route_paths)
        self.assertIn("/api/reports/{report_ref}/validate", route_paths)
        self.assertIn("/api/reports/{report_ref}/render-sql", route_paths)
        self.assertIn("/api/reports/{report_ref}/export-sql", route_paths)

    def test_rule_detail_controls_are_rendered_by_frontend(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")

        self.assertIn("messageInput.addEventListener", app_js)
        self.assertIn("dimensionSelect.addEventListener", app_js)
        self.assertIn("typeSelect.addEventListener", app_js)
        self.assertIn("ruleRowNode", app_js)
        self.assertIn("renderRuleDetail", app_js)
        self.assertIn("rule.message = stripMessagePipe(messageInput.value)", app_js)
        self.assertIn("const newValue = normalizeMessage(messageInput.value)", app_js)
        self.assertIn('return String(value || "").replace(/^\\s*\\|+\\s*/, "")', app_js)
        self.assertIn("ruleDetail", index_html)
        self.assertIn("/assets/app.js?v=", index_html)

    def test_ai_rule_assistant_is_available_in_rule_wizard(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")

        self.assertIn("aiConfigDialog", index_html)
        self.assertIn("Fachliche Regelbeschreibung", app_js)
        self.assertIn("/api/ai/rules/draft", app_js)
        self.assertIn("/api/ai/rules/test-examples", app_js)
        self.assertIn("groupInternalName(group)", app_js)
        self.assertIn('requestJson("/api/ai/configs")', app_js)
        self.assertNotIn("/api/ai/configs?", app_js)
        self.assertIn("aiProfileSelect", index_html)
        self.assertIn("LAST_AI_CONFIG_STORAGE_KEY", app_js)
        self.assertIn('value="openai_compatible"', index_html)
        self.assertIn('value="ollama"', index_html)
        self.assertIn('value="gemini"', index_html)
        self.assertIn("AI_PROVIDER_PRESETS", app_js)

    def test_existing_rule_can_be_explained_by_ai(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("Formel erklären", app_js)
        self.assertIn("/api/ai/rules/explain", app_js)
        self.assertIn("renderRuleExplanation", app_js)
        self.assertIn("function apiDetailText", app_js)
        self.assertIn('detail.map(apiDetailText).filter(Boolean).join("; ")', app_js)
        self.assertIn("projectColumnForGroup", app_js)
        self.assertIn("KI-generierte Erklärung · fachlich prüfen", app_js)
        self.assertIn(".ai-explanation", styles_css)

    def test_existing_rule_can_be_revised_by_ai_and_logged(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("Mit KI überarbeiten", app_js)
        self.assertIn("/api/ai/rules/revise", app_js)
        self.assertIn("Vorschlag übernehmen", app_js)
        self.assertIn('changeType: "rule_ai_revision"', app_js)
        self.assertIn("Beispiele prüfen", app_js)
        self.assertIn(".ai-revision", styles_css)
        self.assertIn(".ai-revision-comparison", styles_css)

    def test_new_group_excludes_used_fields_and_accepts_ai_suggestions(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("usedKeys", app_js)
        self.assertIn("!keys.some((key) => usedKeys.has(key))", app_js)
        self.assertIn("/api/ai/fields/suggest-rules", app_js)
        self.assertIn("KI-Regelvorschläge erzeugen", app_js)
        self.assertIn("anonymisiertes Einspaltenprofil ohne Rohwerte", app_js)
        self.assertIn("suggestionSelections", app_js)
        self.assertIn(".ai-field-suggestion", styles_css)

    def test_rule_groups_are_collapsible(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("expandedGroups", app_js)
        self.assertIn("function toggleAllGroups", app_js)
        self.assertIn("groupToggleBtn", index_html)
        self.assertIn("group-header", styles_css)
        self.assertIn("group-description", styles_css)
        self.assertIn('textBlock("span", description, "group-description")', app_js)
        self.assertIn('String(group.description || "").trim()', app_js)
        self.assertIn("groupPreviewDisplayName", app_js)
        self.assertIn("displayNameNode.title = previewDisplayName", app_js)
        self.assertIn("internalNameNode.title = internalName", app_js)
        self.assertIn("rule-list[hidden]", styles_css)
        self.assertIn("rule-title-button", styles_css)
        self.assertIn("rule-detail", styles_css)

    def test_rule_group_internal_name_is_editable_and_propagated(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")

        self.assertNotIn("internalName.readOnly = true", app_js)
        self.assertIn("function applyGroupInternalName", app_js)
        self.assertIn("rule.condition = replaceInternalName", app_js)
        self.assertIn("attribute.expression = replaceInternalName", app_js)
        self.assertIn('"group_internal_name"', app_js)

    def test_sql_blocks_open_contextual_editor(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("selectedBlockIndex", app_js)
        self.assertIn("selectBlock", app_js)
        self.assertIn("renderBlockDetail", app_js)
        self.assertIn("blockContextField", app_js)
        self.assertIn('"block_metadata"', app_js)
        self.assertIn("detailPanelTitle", index_html)
        self.assertIn("Blockparameter", app_js)
        self.assertIn("MASTER_DATA_SUB_TYPE", app_js)
        self.assertIn("parseSourceExceptionLines", app_js)
        self.assertIn('changeType: block.id === "source" ? "source_configuration"', app_js)
        self.assertIn(".block-item.selected", styles_css)

    def test_middle_column_changes_with_selected_block(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("renderContextPanel", app_js)
        self.assertIn("renderBlockContextItems", app_js)
        self.assertIn("blockContextEntries", app_js)
        self.assertIn("selectContextItem", app_js)
        self.assertIn("renderContextItemDetail", app_js)
        self.assertIn("Attribute und Ausnahmen", app_js)
        self.assertIn("Prozessfilter und Felder", app_js)
        self.assertIn("Verknüpfungen", app_js)
        self.assertIn("Ausgabefelder", app_js)
        self.assertIn("contextPanelTitle", index_html)
        self.assertIn("contextPanelActions", index_html)
        self.assertIn(".context-item.selected", styles_css)

    def test_editor_draft_controls_are_rendered_by_frontend(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")

        self.assertIn("saveDraftBtn", app_js)
        self.assertIn("deleteDraftBtn", app_js)
        self.assertIn("saveEditorDraft", app_js)
        self.assertIn("deleteEditorDraft", app_js)
        self.assertIn("preferDraft", app_js)
        self.assertIn("reportSqlHash", app_js)
        self.assertIn("baseSqlHash", app_js)
        self.assertIn("staleDraftDiscarded", app_js)
        self.assertIn("Draft speichern", index_html)
        self.assertIn("Draft verwerfen", index_html)


    def test_change_log_controls_are_rendered_by_frontend(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("changeLog", app_js)
        self.assertIn("persistRuleChange", app_js)
        self.assertIn("undoLastChange", app_js)
        self.assertIn("/change-log/undo", app_js)
        self.assertIn("undoChangeBtn", index_html)
        self.assertIn("restoreOriginalBtn", index_html)
        self.assertIn("restoreOriginalReport", app_js)
        self.assertIn("/restore-original", app_js)
        self.assertIn("Ursprungsbericht wiederherstellen", index_html)
        self.assertIn("changeLogList", index_html)
        self.assertIn("Änderungsverlauf", index_html)
        self.assertIn("change-log-list", styles_css)

    def test_rule_structure_editor_controls_are_rendered_by_frontend(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("addGroupBtn", index_html)
        self.assertIn("+ Regelgruppe", index_html)
        self.assertIn("addRuleBtn", index_html)
        self.assertIn("openGroupWizard", app_js)
        self.assertIn("ensureSourceAttribute(selectedColumn)", app_js)
        self.assertIn('targetPath: "$"', app_js)
        self.assertIn("openRuleWizard", app_js)
        self.assertIn("Neue Regelgruppe", app_js)
        self.assertIn("Regelgruppe anlegen", app_js)
        self.assertIn("toggleGroupActive", app_js)
        self.assertIn("moveRule", app_js)
        self.assertIn("moveGroup", app_js)
        self.assertIn("deleteGroup", app_js)
        self.assertIn('"group_delete"', app_js)
        self.assertIn('"Regelgruppe entfernen"', app_js)
        self.assertIn("Das Quellattribut bleibt erhalten.", app_js)
        self.assertIn("deleteRule", app_js)
        self.assertIn("persistGroupRulesChange", app_js)
        self.assertIn("openGroupEditor", app_js)
        self.assertIn("enrichGroupColumnMetadata", app_js)
        self.assertIn("flatMap((rule)", app_js)
        self.assertIn("Displayname, Internalname und Beschreibung bearbeiten", app_js)
        self.assertIn('"group_metadata"', app_js)
        self.assertIn('parameterField("Displayname", displayName)', app_js)
        self.assertIn("displayName.value = groupPreviewDisplayName(group)", app_js)
        self.assertIn('parameterField("Internalname", internalName)', app_js)
        self.assertIn("displayName.required = true", app_js)
        self.assertIn("group.displayName = nextDisplayName", app_js)
        self.assertIn("internalName.required = true", app_js)
        self.assertIn("loadProjectColumns", app_js)
        self.assertIn("filterProjectColumns", app_js)
        self.assertIn("selectColumnForBlock", app_js)
        self.assertIn('${column.displayName || ""} ${column.internalName || ""} ${column.importName || ""} ${column.description || ""}', app_js)
        self.assertIn("/api/projects/${encodeURIComponent(state.project)}/columns", app_js)
        self.assertIn("group-actions", styles_css)
        self.assertIn("icon-button", styles_css)
        self.assertIn("column-search-results", styles_css)
        self.assertIn("grid-auto-rows: max-content", styles_css)
        self.assertIn("height: max-content", styles_css)
        self.assertIn(".column-result .column-description", styles_css)

    def test_sql_preview_controls_are_rendered_by_frontend(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("renderSqlBtn", app_js)
        self.assertIn("renderGeneratedSql", app_js)
        self.assertIn("exportGeneratedSql", app_js)
        self.assertIn("downloadBlob", app_js)
        self.assertIn("exportSqlBtn", index_html)
        self.assertIn("writeNemoBtn", index_html)
        self.assertIn("In NEMO speichern", index_html)
        self.assertIn("writeGeneratedSqlToNemo", app_js)
        self.assertIn("overwriteConfirmation", app_js)
        self.assertIn("/write-to-nemo", app_js)
        self.assertIn("TOP-25-Bericht wird auf 25 Zeilen begrenzt", app_js)
        self.assertIn("payload.updatedReports", app_js)
        self.assertIn("payload.sql || payload.generatedChecksSql", app_js)
        self.assertIn("SQL-Vorschau vollständig", app_js)
        self.assertIn("sqlPreview", index_html)
        self.assertIn('id="sqlPreviewPanel"', index_html)
        self.assertIn("showSqlDetail", app_js)
        self.assertIn("showParameterDetail", app_js)
        self.assertIn("detail-sql-active", app_js)
        self.assertIn("sql-preview", styles_css)
        self.assertIn(".rule-parameter-section", styles_css)
        self.assertIn("position: sticky", styles_css)
        self.assertIn("Vollständiges SQL generiert", app_js)

    def test_editor_first_workflow_is_rendered_by_frontend(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")

        self.assertIn('activeView: "editor"', app_js)
        self.assertIn('nemo-last-config-id', app_js)
        self.assertIn('localStorage.getItem(LAST_CONFIG_STORAGE_KEY)', app_js)
        self.assertIn('localStorage.setItem(LAST_CONFIG_STORAGE_KEY, state.configId)', app_js)
        self.assertIn('await switchView("editor")', app_js)
        self.assertLess(index_html.index('id="editorViewBtn"'), index_html.index('id="resultViewBtn"'))
        self.assertIn('<div id="resultView" class="view-panel expert-only" hidden>', index_html)
        self.assertIn('<div id="editorView" class="view-panel">', index_html)
    def test_sidebar_can_be_collapsed(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("sidebarToggleBtn", index_html)
        self.assertIn("sidebar-content", index_html)
        self.assertIn("applySidebarState", app_js)
        self.assertIn("nemo-sidebar-collapsed", app_js)
        self.assertIn("sidebar-collapsed", styles_css)

    def test_active_tenant_is_rendered_in_header(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("activeConfig", app_js)
        self.assertIn("setConnectionState", app_js)
        self.assertIn("tenant", app_js)
        self.assertIn("brand-text", index_html)
        self.assertIn("20260907-rulebook-export", index_html)
        self.assertIn(".brand-text", styles_css)

    def test_standard_and_expert_modes_are_rendered_by_frontend(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="standardModeBtn"', index_html)
        self.assertIn('id="expertModeBtn"', index_html)
        self.assertIn("nemo-ui-mode", app_js)
        self.assertIn("function applyUiMode", app_js)
        self.assertIn("selectChecksBlockForStandard", app_js)
        self.assertIn('await applyUiMode(localStorage.getItem(UI_MODE_STORAGE_KEY) || "standard")', app_js)
        self.assertIn(".mode-standard .expert-only", styles_css)
        self.assertIn(".mode-standard .editor-grid", styles_css)

    def test_report_selection_shows_loading_indicator(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn("loadingReportRef", app_js)
        self.assertIn('spinner.className = "report-spinner"', app_js)
        self.assertIn('button.setAttribute("aria-busy", String(isLoading))', app_js)
        self.assertIn(".report-spinner", styles_css)
        self.assertIn("@keyframes report-spin", styles_css)

    def test_write_refreshes_stale_report_for_selected_config(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")

        self.assertIn("ensureFreshReportBeforeWrite", app_js)
        self.assertIn("updateActiveConfigTenant(payload.configTenant)", app_js)
        self.assertIn("Bericht wurde für die ausgewählte Konfiguration neu geladen", app_js)
        self.assertIn('clearEditor("Konfiguration gewechselt - Bericht wird neu geladen")', app_js)
        self.assertIn("return report.internalName || report.id || report.displayName", app_js)
        self.assertIn("20260907-rulebook-export", index_html)

    def test_config_can_be_created_from_credentials_dialog(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="addConfigBtn"', index_html)
        self.assertIn('id="editConfigBtn"', index_html)
        self.assertIn('id="configDialog"', index_html)
        self.assertIn('id="configNameInput"', index_html)
        self.assertIn('id="configTenantInput"', index_html)
        self.assertIn('id="configUserIdInput"', index_html)
        self.assertIn('id="configPasswordInput"', index_html)
        self.assertIn('id="configNemoUrlInput"', index_html)
        self.assertIn('id="configEnvironmentInput"', index_html)
        self.assertIn('id="deleteConfigBtn"', index_html)
        self.assertIn('type="password"', index_html)
        self.assertIn("saveConfigFromDialog", app_js)
        self.assertIn("openEditConfigDialog", app_js)
        self.assertIn("deleteConfigFromDialog", app_js)
        self.assertIn('"/api/configs/from-credentials"', app_js)
        self.assertIn("/connection`", app_js)
        self.assertIn('elements.configPasswordInput.value = ""', app_js)
        self.assertIn(".config-dialog", styles_css)
        self.assertIn("20260907-rulebook-export", index_html)

    def test_configuration_statistics_can_be_created_and_exported(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="configStatisticsBtn"', index_html)
        self.assertIn('id="configStatisticsDialog"', index_html)
        self.assertIn('id="configStatisticsTable"', index_html)
        self.assertIn('id="statisticsActiveBar"', index_html)
        self.assertIn("function openConfigStatistics", app_js)
        self.assertIn("/api/config-statistics", app_js)
        self.assertIn("function renderConfigStatistics", app_js)
        self.assertIn("function exportConfigRulebook", app_js)
        self.assertIn('id="exportConfigStatisticsPdfBtn"', index_html)
        self.assertIn('id="exportConfigStatisticsExcelBtn"', index_html)
        self.assertIn('id="configStatisticsSourceSelect"', index_html)
        self.assertIn('id="configStatisticsTop25Input"', index_html)
        self.assertIn("/api/config-statistics/report.${format}", app_js)
        self.assertIn(".statistics-status-bar", styles_css)
        self.assertIn(".statistics-table-wrap", styles_css)
        self.assertIn(".statistics-options", styles_css)

    def test_existing_master_data_rules_can_be_analyzed_for_catalog(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="analyzeExistingRulesBtn"', index_html)
        self.assertIn('id="ruleTemplateAnalysisPanel"', index_html)
        self.assertIn('id="ruleTemplateCandidateList"', index_html)
        self.assertIn("/api/rule-templates/analyze-existing", app_js)
        self.assertIn("/api/rule-templates/import-existing", app_js)
        self.assertIn("function analyzeExistingRules", app_js)
        self.assertIn("function importRuleTemplateCandidates", app_js)
        self.assertIn("state.ruleTemplateAnalysis = null", app_js)
        self.assertIn(".rule-template-candidate", styles_css)
        self.assertIn('id="ruleTemplateCandidateDetail"', index_html)
        self.assertIn('id="rejectRuleTemplateCandidateBtn"', index_html)
        self.assertIn('id="importSingleRuleTemplateCandidateBtn"', index_html)
        self.assertIn("function renderRuleTemplateCandidateDetail", app_js)
        self.assertIn("function setSelectedRuleTemplateCandidateDecision", app_js)
        self.assertIn("/api/rule-templates/candidate-decisions", app_js)
        self.assertIn(".candidate-location-list", styles_css)

    def test_harmonization_matrix_is_rendered_by_frontend(self) -> None:
        app_js = (FRONTEND_DIR / "app.js").read_text(encoding="utf-8")
        index_html = (FRONTEND_DIR / "index.html").read_text(encoding="utf-8")
        styles_css = (FRONTEND_DIR / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="harmonizationViewBtn"', index_html)
        self.assertIn('id="harmonizationMatrix"', index_html)
        self.assertIn("function loadHarmonization", app_js)
        self.assertIn("/api/harmonization", app_js)
        self.assertIn("function renderHarmonizationDetail", app_js)
        self.assertIn("function previewHarmonizationTransfer", app_js)
        self.assertIn("function applyHarmonizationTransfer", app_js)
        self.assertIn("/api/harmonization/preview", app_js)
        self.assertIn("/api/harmonization/apply", app_js)
        self.assertIn(".harmonization-grid", styles_css)
        self.assertIn(".harmonization-status.divergent", styles_css)
        self.assertIn("harmonization-rule-counts", app_js)
        self.assertIn("occurrence.activeRuleCount", app_js)
        self.assertIn(".harmonization-rule-active", styles_css)
        self.assertIn(".harmonization-rule-inactive", styles_css)
        self.assertIn("harmonizationDifferencePanel", app_js)
        self.assertIn("occurrence.differences", app_js)
        self.assertIn(".harmonization-difference-item", styles_css)
        self.assertIn(".harmonization-transfer-preview", styles_css)
if __name__ == "__main__":
    unittest.main()
